services:
  app:
    image: gutenye/supercronic
    entrypoint: /usr/bin/supercronic -json crontab
    tty: true
    build:
      platforms:
        - linux/arm64
        - linux/amd64
    volumes:
      - ./data/crontab:/crontab
